[tool.poetry]
name = "zalo"
version = "0.1.0"
description = ""
authors = ["Bui Thu Ha <thuhak22ba@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.9"
black = "^22.12.0"
Flask = "^2.2.2"
SQLAlchemy = "^1.4.45"
flask-marshmallow = "^0.14.0"
Flask-RESTful = "^0.3.9"
flask-sqlalchemy = "^3.0.2"
psycopg2 = "^2.9.5"
Flask-Migrate = "^4.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
